### ISSUE TITLE
Unexpected levenshtein_distance output

### ISSUE THREAD

**Issue by iamanigeeit** [1ytic/pytorch-edit-distance#3]
```
xs = torch.tensor([[1, 1, 1, 1, 1], [2, 2, 2, 2, 2]], dtype=torch.int).cuda()
ys = torch.tensor([[8, 8, 8, 8, 8], [9, 9, 9, 9, 9]], dtype=torch.int).cuda()
lens = torch.tensor([5,5], dtype=torch.int).cuda()
blank = torch.tensor([0], dtype=torch.int).cuda()
sep = torch.tensor([-1], dtype=torch.int).cuda()
levenshtein_distance(xs, ys, y_len, y_len, blank, sep)
```
Output:
```
tensor([[0, 0, 1, 1],
        [0, 0, 1, 1]], device='cuda:0', dtype=torch.int32)
```

Is the output just boolean? Based on normal Levenshtein distance calculation it should be 5 edits, right?

**Comment by 1ytic** [comment]
This behaviour is correct. You must include the blank symbol between each unit and make the sep symbol empty. Please look at [test](https://github.com/1ytic/pytorch-edit-distance/blob/master/torch_edit_distance/test.py) examples.

**Comment by iamanigeeit** [comment]
I see. The xs and ys are token sequences including blanks and separators and Levenshtein distance is based on words. I was looking for the classical string Levenshtein distance. Thanks.
