### ISSUE TITLE
question about specify blank and sep when computing cer ?

### ISSUE THREAD

**Issue by songtaoshi** [1ytic/pytorch-edit-distance#4]
Hi, 1ytic, thanks for your nice implementation of edit-distance in cuda!    

I am wondering that when I am computing the cer, is it still needed to specify the blank and sep.  

I have seen the code in **edit-distance.cu**. It seems that we still have to put the blank and sep, and do some redundant computation.  

Do I understand right? or We still need the blank and sep in computing cer?

**Comment by 1ytic** [comment]
Thank you, @songtaoshi. My implementation has some general form and is mostly suitable for CTC-like models. This means that you always have a blank token. Moreover, in general, when calculating CER, a space token is also ignored. Thus I combine both tokens [here](https://github.com/1ytic/pytorch-edit-distance/blob/8d91eb02be4cb85a764c627cd8a7db54d0943751/torch_edit_distance/__init__.py#L152). Anyway, if you do not want to ignore tokens, you can specify an empty blank and separation tensor like [this](https://github.com/1ytic/pytorch-edit-distance/blob/8d91eb02be4cb85a764c627cd8a7db54d0943751/torch_edit_distance/__init__.py#L153).

**Comment by songtaoshi** [comment]
Understand! Thanks for your reply !
