### ISSUE TITLE
bug or cofusion about the AverageCER meter.

### ISSUE THREAD

**Issue by songtaoshi** [1ytic/pytorch-edit-distance#5]
hi 1ytic, 
![image](https://user-images.githubusercontent.com/20240391/86618956-56f05700-bfec-11ea-9a83-f3c49cb7ff0c.png)
![image](https://user-images.githubusercontent.com/20240391/86619224-c6fedd00-bfec-11ea-8d0e-22a66104cb42.png)

Actually, I have successfully run the AverageCER in your e2e ctc training. But I have met a problem. It seems that the self.data initial is zero cannot be added to the cuda tensor, but I have tried 0+cuda_tensor

**Comment by 1ytic** [comment]
If I remember correctly, this happens when the local CUDA version does not match with torch. Try to install torch-edit-distance in the system with CUDA version equal to torch CUDA.

**Comment by songtaoshi** [comment]
![image](https://user-images.githubusercontent.com/20240391/86724416-580c9d00-c05b-11ea-9a58-0df24da51dec.png)

Hi, still meets problem.  maybe it can only be used to CUDA 10.0 or are there any setting I need to check?

**Comment by 1ytic** [comment]
Did you rebuild the package with pip --no-cache-dir ? If this does not help, please try to manually replace all `AT_DISPATCH_ALL_TYPES` with `AT_DISPATCH_INTEGRAL_TYPES` in the file [edit-distance.cu](https://github.com/1ytic/pytorch-edit-distance/blob/master/edit-distance.cu) and rebuild the package locally.

**Comment by songtaoshi** [comment]
![image](https://user-images.githubusercontent.com/20240391/86777132-5c50ae80-c08b-11ea-9452-a11f371cd1fa.png)
pip install no cache tried but still have problem and I have not tried yet edit the type in .cu file.

**Comment by songtaoshi** [comment]
and also tried replacing all the AT_DISPATCH_ALL_TYPES with AT_DISPATCH_INTEGRAL_TYPES, and rebuild with python setup.py install but it still not works

**Comment by 1ytic** [comment]
Did you run python -m torch_edit_distance.test?

**Comment by songtaoshi** [comment]
The result:
![image](https://user-images.githubusercontent.com/20240391/86787428-a770be80-c097-11ea-8cd7-5540b0f32218.png)

**Comment by 1ytic** [comment]
It is definitely something bad with CUDA. Try reinstalling everything in an isolated environment :(
