### ISSUE TITLE
Is there any docs for the lib?  Is there a way to  find out which tensor value is to be 'delete' ?

### ISSUE THREAD

**Issue by CheungZeeCn** [1ytic/pytorch-edit-distance#6]
input is a pair of tensors, with different shape maybe:
# 0 for begin, 2 for end, 1 for padding

a = [[0, 6, 2, 1, 1]
        [0, 7,  8, 6, 2]]
b = [[0, 7, 2,  1]
        [0, 8, 5, 2]]

what I want is a mask_tensor:
c = [[0, 1, 0, 0, 0]
        [0, 1,  0, 1, 0]]
 if we want to change a ->b,   the units in c indicate which unit in a should be deleted;

or can we get the final tensor like: (after the delete ops in a, we get d)
d = [[0, 2, 1]
        [0, 8, 2]]

thx

**Comment by 1ytic** [comment]
If I understand correctly, you are asking for a path in [Edit Distance Matrix](https://en.wikipedia.org/wiki/Levenshtein_distance). Unfortunately, in this library, I only implement the distance function.

**Comment by CheungZeeCn** [comment]
Thank you all the same!
