### ISSUE TITLE
Does it supports torch CPU?

### ISSUE THREAD

**Issue by KinWaiCheuk** [1ytic/pytorch-edit-distance#7]
I have a machine with only CPU for debugging. However, I am unable to install your library via `pip install torch_edit_distance`. The following errors appear

> OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
> ERROR: Could not find a version that satisfies the requirement torch_edit_distance
> ERROR: No matching distribution found for torch_edit_distance

**Comment by 1ytic** [comment]
Unfortunately, you can't install it on a machine without GPU.
